services:

  #  rabbitmq:
  #    image: rabbitmq
  #    container_name: 'rabbitmq'
  #    ports:
  #      - 5672:5672
  #      - 15672:15672
  #    volumes:
  #      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  #      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  #    networks:
  #      - backend-network

  api-gateway-service:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    environment:
      - ENV=production
    depends_on:
      - auth-service
    networks:
      - backend-network

  auth-service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "8005:8001"
    environment:
      - ENV=production
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
